# Generated by Django 3.2.5 on 2021-07-04 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenterCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_center_name', models.CharField(max_length=100)),
                ('sqr_mtr', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=5, unique=True)),
                ('other_info', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_assest_tag', models.CharField(error_messages={'unique': 'Device already exists.'}, max_length=15, unique=True)),
                ('make_and_model', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('device_serial_no', models.IntegerField(default=0)),
                ('wattage', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('no_of_power_supplies', models.CharField(max_length=50)),
                ('no_of_ports', models.IntegerField()),
                ('special_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('day_started', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Postname', models.CharField(max_length=30)),
                ('Postemail', models.EmailField(blank=True, max_length=254)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_user', models.BooleanField(default=True)),
                ('bio', models.TextField(default='NO BIO')),
                ('master_password', models.CharField(default='Test@123', max_length=32)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagePermissionForGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_page', models.CharField(max_length=30)),
                ('all_perm', models.BooleanField(default=False)),
                ('read_perm', models.BooleanField(default=False)),
                ('write_perm', models.BooleanField(default=False)),
                ('delete_perm', models.BooleanField(default=False)),
                ('update_perm', models.BooleanField(default=False)),
                ('patch_perm', models.BooleanField(default=False)),
                ('groupname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='DataCenterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=100)),
                ('data_center_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('sqr_mtr', models.PositiveIntegerField(blank=True, default=0)),
                ('other_info', models.TextField(blank=True, default='')),
                ('link_dc', models.URLField(default='https://www.google.com/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.datacentercountry')),
            ],
        ),
    ]
