# Generated by Django 3.2.5 on 2021-07-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_websitelinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_center_name', models.CharField(max_length=50)),
                ('sqr_mtr', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=50)),
            ],
        ),
    ]
