# Generated by Django 3.2.5 on 2021-07-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='addDataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCenterTag', models.CharField(blank=True, max_length=30)),
                ('DataCenterName', models.CharField(blank=True, max_length=30)),
                ('sqr_mtr', models.PositiveIntegerField(blank=True, default=0)),
                ('delAdd_country', models.CharField(blank=True, max_length=30)),
                ('delAdd_state', models.CharField(blank=True, max_length=255, null=True)),
                ('delAddress', models.CharField(blank=True, max_length=100)),
                ('Contact', models.CharField(blank=True, max_length=100)),
                ('PersonalDet_fname', models.CharField(blank=True, max_length=128)),
                ('PersonalDet_email', models.EmailField(blank=True, max_length=100)),
                ('Capacity_in_MW', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AddDataCenterRackcabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RackRow', models.CharField(blank=True, max_length=1)),
                ('Rack_Label_Tag', models.CharField(blank=True, max_length=10)),
                ('RowColor', models.CharField(blank=True, max_length=10)),
                ('Rack_Type', models.CharField(blank=True, max_length=50)),
                ('Rack_Type_Information', models.CharField(blank=True, max_length=50)),
                ('Owner', models.CharField(blank=True, max_length=50)),
                ('Patch_Panels_Ethernet', models.CharField(max_length=50)),
                ('Patch_Panels_Fiber', models.CharField(max_length=50)),
                ('Patch_Panels_Other', models.CharField(max_length=50)),
                ('Special_Notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='addDataCenterRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RackRow', models.CharField(blank=True, max_length=10)),
                ('Row_Label_Tag', models.CharField(blank=True, max_length=30)),
                ('RowColor', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
