# Generated by Django 3.2.5 on 2021-07-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210707_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='RR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RackRow', models.CharField(max_length=50)),
                ('rack_label', models.CharField(max_length=50)),
                ('rack_label_colour', models.CharField(max_length=50)),
                ('assest_tag', models.CharField(max_length=15, unique=True)),
                ('make_and_model', models.CharField(max_length=50)),
                ('rack_type', models.CharField(max_length=50)),
                ('client_department', models.CharField(max_length=50)),
                ('patch_panels', models.CharField(max_length=50)),
                ('power_load', models.CharField(max_length=50)),
                ('special_notes', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='adddevice',
            name='load_type_both',
        ),
        migrations.RemoveField(
            model_name='adddevice',
            name='patch_patch_type',
        ),
        migrations.RemoveField(
            model_name='adddevice',
            name='ports_type_both',
        ),
        migrations.RemoveField(
            model_name='adddevice',
            name='ports_type_ehthernet',
        ),
        migrations.RemoveField(
            model_name='adddevice',
            name='ports_type_fibre',
        ),
        migrations.RemoveField(
            model_name='adddevice',
            name='storage_capacity',
        ),
        migrations.RemoveField(
            model_name='adddevice',
            name='tapelib_capacity',
        ),
        migrations.AddField(
            model_name='adddevice',
            name='patch_category_type_cross',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='patch_category_type_inter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='patch_category_type_isp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='patch_category_type_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='storage_capicity_input',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='storage_capicity_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='tapelib_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
