# Generated by Django 3.2.5 on 2021-07-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_adddatacenterrow_data_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddatacenterrackcabinet',
            name='date_center_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.adddatacenterrow'),
        ),
    ]
