# Generated by Django 3.2.5 on 2021-07-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_adddatacenterrackcabinet_date_center_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddatacenterrackcabinet',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.adddatacenter'),
        ),
    ]
