# Generated by Django 3.2.5 on 2021-07-14 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_adddevice_cctv_url'),
        ('dashboard', '0018_remove_adddatacenterrackcabinet_rackrow'),
    ]

    operations = [
    ]
