# Generated by Django 3.2.5 on 2021-07-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_merge_20210714_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddevice',
            name='data_center_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.adddatacenterrackcabinet'),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.adddatacenter'),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='date_center_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.adddatacenterrow'),
        ),
    ]
