# Generated by Django 3.2.5 on 2021-07-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_adddatacenterrackcabinet_rack_type_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddevice',
            name='Rack_Location',
        ),
        migrations.RemoveField(
            model_name='adddevice',
            name='Row_Location',
        ),
    ]
