# Generated by Django 3.2.5 on 2021-07-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20210715_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddevice',
            name='device_height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
