# Generated by Django 3.2.5 on 2021-07-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_devicedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedetails',
            name='patchpanel_incoming',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedetails',
            name='patchpanel_outgoing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
