# Generated by Django 3.2.5 on 2021-07-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20210720_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddatacenterrackcabinet',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
