# Generated by Django 3.2.5 on 2021-07-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptime',
            name='startingTime',
            field=models.DateTimeField(),
        ),
    ]
