# Generated by Django 3.2.5 on 2021-07-21 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_adddatacenterrackcabinet_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('incoming', models.IntegerField(blank=True, null=True)),
                ('outgoing', models.IntegerField(blank=True, null=True)),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.adddatacenterrackcabinet')),
            ],
        ),
    ]
