# Generated by Django 3.2.5 on 2021-07-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_patchpanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchpanel',
            name='incoming',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patchpanel',
            name='outgoing',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PatchPanelPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(blank=True, null=True)),
                ('information', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.adddevice')),
                ('patchpanel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.patchpanel')),
            ],
        ),
    ]
