# Generated by Django 3.2.5 on 2021-07-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20210721_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchpanelport',
            name='information',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
