# Generated by Django 3.2.5 on 2021-07-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_uptime_startingtime'),
        ('dashboard', '0029_alter_patchpanelport_information'),
    ]

    operations = [
    ]
