# Generated by Django 3.2.5 on 2021-07-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_merge_20210721_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchpanelport',
            name='in_out',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
