# Generated by Django 3.2.5 on 2021-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_patchpanelport_patchpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddevice',
            name='type_of_device',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
