# Generated by Django 3.2.5 on 2021-07-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_adddevice_type_of_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessUtil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('utilpercentage', models.FloatField(default=0.0)),
            ],
        ),
    ]
