# Generated by Django 3.2.5 on 2021-07-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_processutil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrome', models.CharField(blank=True, max_length=50, null=True)),
                ('firefox', models.CharField(blank=True, max_length=50, null=True)),
                ('mozilla', models.CharField(blank=True, max_length=50, null=True)),
                ('safari', models.CharField(blank=True, max_length=50, null=True)),
                ('others', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
