# Generated by Django 3.2.5 on 2021-07-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20210723_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series1', models.FloatField(default=0.0)),
                ('series2', models.FloatField(default=0.0)),
            ],
        ),
    ]
