# Generated by Django 3.2.5 on 2021-07-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddevice',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
