# Generated by Django 3.2.5 on 2021-07-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_adddevice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddevice',
            name='deviceConn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='deviceMake',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='deviceModel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='deviceOwner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='deviceSupplies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='deviceWatt',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adddevice',
            name='installDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
