# Generated by Django 3.2.5 on 2021-07-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_devicetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetemplate',
            name='templatename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
