# Generated by Django 3.2.5 on 2021-07-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_devicetemplate_templatename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetemplate',
            name='data_center_rack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicetemplate',
            name='datacenter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicetemplate',
            name='date_center_row',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
