# Generated by Django 3.2.5 on 2021-07-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20210728_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='gitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series1', models.FloatField(default=0.0)),
            ],
        ),
    ]
