# Generated by Django 3.2.5 on 2021-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_gittest_series2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(default=True, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='gitTest',
        ),
    ]
