# Generated by Django 3.2.5 on 2021-07-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20210730_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetemplate',
            name='ownerDesc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
