# Generated by Django 3.2.5 on 2021-08-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_adddevice_ownerdesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddatacenter',
            old_name='delAdd_country',
            new_name='Add_country',
        ),
        migrations.RenameField(
            model_name='adddatacenter',
            old_name='delAdd_state',
            new_name='Add_state',
        ),
        migrations.RenameField(
            model_name='adddatacenter',
            old_name='delAddress',
            new_name='Address',
        ),
    ]
