# Generated by Django 3.2.5 on 2021-08-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_devicecapibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecapibility',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecapibility',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
