# Generated by Django 3.2.5 on 2021-08-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_auto_20210803_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecapibility',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
