# Generated by Django 3.2.5 on 2021-08-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_alter_devicecapibility_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecapibility',
            name='schedule',
            field=models.DateField(blank=True, null=True),
        ),
    ]
