# Generated by Django 3.2.5 on 2021-08-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_devicecapibility_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddevice',
            old_name='status',
            new_name='power_left',
        ),
        migrations.AddField(
            model_name='adddevice',
            name='power_right',
            field=models.BooleanField(default=True),
        ),
    ]
