# Generated by Django 3.2.5 on 2021-08-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_alter_raiseticket_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiseticket',
            name='fname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raiseticket',
            name='lname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raiseticket',
            name='msg',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
