# Generated by Django 3.2.5 on 2021-08-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_auto_20210818_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiseticket',
            name='in_progress',
        ),
        migrations.RemoveField(
            model_name='raiseticket',
            name='is_solved',
        ),
        migrations.AddField(
            model_name='raiseticket',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raiseticket',
            name='admin_response',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
