# Generated by Django 3.2.5 on 2021-08-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20210818_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiseticket',
            name='admin_response',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
