# Generated by Django 3.2.5 on 2021-08-18 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_alter_raiseticket_admin_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raiseticket',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
