# Generated by Django 3.2.5 on 2021-08-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_auto_20210818_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='raiseticket',
            name='is_aprove',
            field=models.BooleanField(default=False),
        ),
    ]
