# Generated by Django 3.2.5 on 2021-01-01 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_ansibleoutput'),
        ('dashboard', '0072_raiseticket_is_aprove'),
    ]

    operations = [
    ]
